name: Testes Automatizados

on: [push]

jobs: 
  testes: 
    name: Testes TDD 
    runs-on: ubuntu-latest

    steps: 
    - name: Checkou Código
      uses: actions/checkout@v2

    - name: Configurar Python
      uses: actions/setup-python@v2

    - name: Instalar dependências
      run: pip install pytest coverage

    - name: Rodar pytest
      run: pytest

    - name: Run Codecov
      run: coverage run -m pytest 

    - name: Upload Codecov
      uses: codecov/codecov-action@v3
      env:
        CODECOV_TOKEN: ba9f3841-54e5-4dc6-b990-28dfd68c001b